### ISSUE TITLE
Use with <audio>

### ISSUE THREAD

**Issue by Deliaz** [cwilso/volume-meter#4]
Hi!
How can I use it with playing mp3 from <audio /> tag ?

**Comment by cwilso** [comment]
Instead of the getUserMedia call that grabs input from the microphone (https://github.com/cwilso/volume-meter/blob/master/main.js#L42-L65), you'd need to call createMediaElementSource() with the audio element:

    // presuming <audio id="my_source">...
    
    var audioSrc = audioContext.createMediaElementSource( document.getElementByID("my_source") );
    
    audioSrc.connect( audioContext.destination );  // you need to connect it to output, or it won't play
    // Create a new volume meter and connect it.
    meter = createAudioMeter(audioContext);
    audioSrc.connect(meter);

Note that the MP3 source will need to be on the same domain as your page; we don't allow cross-domain media element source creation without CORS.
